-------------------------------------------------------
-- 				DDL FOR TABLE 'COMERCIO'			 --
-------------------------------------------------------

CREATE TABLE COMERCIO (
    id_comercio INT GENERATED BY DEFAULT AS IDENTITY
    ,nom_comercio VARCHAR(200)
    ,aforo_maximo INT
    ,PRIMARY KEY(id_comercio)
);
