-------------------------------------------------------
-- 				DDL FOR TABLE 'SERVICIO'			 --
-------------------------------------------------------

CREATE TABLE SERVICIO (
    id_servicio INT GENERATED BY DEFAULT AS IDENTITY
    ,id_comercio INT
	,nom_servicio VARCHAR(200)
    ,hora_apertura VARCHAR(8)
    ,hora_cierre VARCHAR(8)
	,duracion INT
    ,PRIMARY KEY(id_servicio)
    ,FOREIGN KEY(id_comercio) REFERENCES COMERCIO(id_comercio)
);
