-------------------------------------------------------
-- 				DDL FOR TABLE 'TURNO'				 --
-------------------------------------------------------

CREATE TABLE TURNO (
    id_turno INT GENERATED BY DEFAULT AS IDENTITY
    ,id_servicio INT
	,fecha_turno VARCHAR(200)
    ,hora_inicio VARCHAR(8)
    ,hora_fin VARCHAR(8)
	,estado VARCHAR(15)
    ,PRIMARY KEY(id_turno)
    ,FOREIGN KEY(id_servicio) REFERENCES SERVICIO(id_servicio)
);
